# Generated by Django 5.1.3 on 2024-11-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='price',
        ),
        migrations.AlterField(
            model_name='kategori',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nama Kategori'),
        ),
        migrations.AlterField(
            model_name='product',
            name='bahan',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='merek_produk',
            field=models.CharField(max_length=50),
        ),
    ]
